### ISSUE TITLE
yabridge vs linvst

### ISSUE THREAD

**Issue by Levitanus** [ElizabethHarmon/ManjaroProAudio#2]
I've found that `LinVst` is still more stable than `yabridge`. I cannot say is it connected exclusevly with GUI, but I have troubles with opening GUI of `Superior Drummer` and `KONTAKT` through `yabridge` time to time.

But I have feeling, that `LinVst` leaks some features connected to flushing, e.g. in large projects CPU usage is very intensive even when project is stopped. 

Also, `yabrifge` has stable repository in Aur, while `LinVst` requires manual installation (I've had troubles with Aur repo).

So, there are pros and cons for both of them, which I think, should be investigated and documented)

**Comment by ElizabethHarmon** [comment]
Thanks for writing. I'm glad that you have enjoyed success but I cannot recommend LinVST to anyone at this point. Everyone I know seems to have shifted to Yabridge including the popular AV Linux distro which seemed like a sort of last stand. I'm also pretty sure that Yabridge came into being because of deficiencies that the LinVST dev was not willing to fix. From my own testing, VST2 and 3 performance via yabridge is vastly superior. 

It might be worth reaching out to Robbert VdH on the yabridge discord if you want to investigate the GUI issues further. He's super helpful and very quick at pushing fixes.
